name: Image Scanner

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'images/**/Dockerfile'

jobs:
  ImageScanner:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     images: [ nginx ] 
    #outputs:
    #  #format('{0}', matrix.images): ${{ steps.pull.outputs[format('{0}', matrix.images)] }}
    #  SHA: ${{ steps.pull.outputs.SHA }}
    
    steps:        
          # Checkout Repo
          - name: Check out the repository
            uses: actions/checkout@v4
          
          # Pull Latest Images
          - name: Check Changes Files
            id: check
            run: |
                ls -l
                git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
                #git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | Where-Object {$_ -CLike "*/Dockerfile"} | ForEach-Object { Write-Host "$_"}
                
